{% set version = "0.3" %}

package:
  name: python-markdown-math
  version: {{ version }}

source:
  fn: python-markdown-math-0.2.tar.gz
  url: https://pypi.io/packages/source/p/python-markdown-math/python-markdown-math-{{ version }}.tar.gz
  sha256: c1b9cb018eb54e14609d1d1cc2ae49f6869b75a459d8a0ce759e6e6ee775d394

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - markdown

test:
  imports:
    - mdx_math

about:
  home: https://github.com/mitya57/python-markdown-math
  license: BSD 3-Clause
  summary: 'Math extension for Python-Markdown.'

extra:
  recipe-maintainers:
    - ocefpaf
