{% set version = "0.5" %}

package:
  name: python-markdown-math
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-markdown-math/python-markdown-math-{{ version }}.tar.gz
  sha256: 8f8803c92ac0847d18bd82a51fdb6acec90b2b54a4990650e627a0d4d3a78445

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - markdown

test:
  imports:
    - mdx_math

about:
  home: https://github.com/mitya57/python-markdown-math
  license: BSD 3-Clause
  summary: 'Math extension for Python-Markdown.'

extra:
  recipe-maintainers:
    - ocefpaf
