travis:
  secure:
    BINSTAR_TOKEN: GqTZhwc8thLfQMgK+gjqqW6hjceoXwThFO+kfFM98AspRHN+aup+blVHWIM3XkA8+XK1fQ/b0WOWZrN9y3EFxxT36sMb2hsC/Y5AlmGZ6xNSAoTMsGt5T6yl+iTUwxHEvXCNAbf0nyj6ac8VriVgLjsK6YAXFiL2nOM23OosKoyu0NAWLXtGlyt6oAYGX8IFn/g4ePMAnHmpmbS3KJtrTuLJosBHMqn82t1PbNNlmQCGMCSK/jKCfTiEBui7MbfBpixGKWl4CGztV/Vxs4c86bMRhtVVhe1jxYTYuYisAc2AehOo1lqwT7c13iWPHcyFHsafQZazHxZelkCpFSbSOZUURRvSWp/yLo18uAUNtJVp3DJA43H5NELdSM0YXV+agB1eutHgz8ZyqHMs9KLObetUH7CwR574/4WS992qwhvKKVQnXQLIYzhz7/H1cLNer09cvyy0fNl9YnKUJISpE3G6rv0jpVfpGvWaduZ/vyPizYtDmnJMXN+nirWssH05m7qWs5nN700B3X1NZE4kSdy/bY6RWXVjX47dAUBnL7jrGCKh/kbw1mqkWIZpUXjVBbAQ4wmcAW8PDnDk0sPMwOv9Bp99NO4pBXZZnctgi2HgZ7kbjWmk5E/mYVPvBmB2IA7jCpZ/AeMOlUONyk5u3+Bgbrq9HkuH2JfCcDP+M34=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
